package com.thermalstrategies.eportal.model;
// Generated Oct 7, 2009 7:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Buildingfloor generated by hbm2java
 */
public class Buildingfloor  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Building building;
     private String floorName;
     private Integer sequenceNum;
     private Set<Dampertest> dampertests = new HashSet<Dampertest>(0);
     private Set<Userlog> userlogs = new HashSet<Userlog>(0);

    public Buildingfloor() {
    }

	
    public Buildingfloor(Integer id) {
        this.id = id;
    }
    public Buildingfloor(Integer id, User user, Building building, String floorName, Integer sequenceNum, Set<Dampertest> dampertests, Set<Userlog> userlogs) {
       this.id = id;
       this.user = user;
       this.building = building;
       this.floorName = floorName;
       this.dampertests = dampertests;
       this.userlogs = userlogs;
       this.sequenceNum = sequenceNum;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Building getBuilding() {
        return this.building;
    }
    
    public void setBuilding(Building building) {
        this.building = building;
    }
    public String getFloorName() {
        return this.floorName;
    }
    
    public void setFloorName(String floorName) {
        this.floorName = floorName;
    }
    public Set<Dampertest> getDampertests() {
        return this.dampertests;
    }
    
    public void setDampertests(Set<Dampertest> dampertests) {
        this.dampertests = dampertests;
    }
    public Set<Userlog> getUserlogs() {
        return this.userlogs;
    }
    
    public void setUserlogs(Set<Userlog> userlogs) {
        this.userlogs = userlogs;
    }

    /**
     * @return the sequenceNum
     */
    public Integer getSequenceNum() {
        return sequenceNum;
    }

    /**
     * @param sequenceNum the sequenceNum to set
     */
    public void setSequenceNum(Integer sequenceNum) {
        this.sequenceNum = sequenceNum;
    }

}


