package com.thermalstrategies.eportal.model;
// Generated Oct 7, 2009 7:19:35 PM by Hibernate Tools 3.2.1.GA



/**
 * Dampercomment generated by hbm2java
 */
public class Dampercomment  implements java.io.Serializable {


     private Integer id;
     private String comment;
     private boolean isenabled;

    public Dampercomment() {
    }

	
    public Dampercomment(Integer id, boolean isenabled) {
        this.id = id;
        this.isenabled = isenabled;
    }
    public Dampercomment(Integer id, String comment, boolean isenabled) {
       this.id = id;
       this.comment = comment;
       this.isenabled = isenabled;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public boolean isIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(boolean isenabled) {
        this.isenabled = isenabled;
    }




}


