package com.thermalstrategies.eportal.model;
// Generated Oct 7, 2009 7:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Damperstatus generated by hbm2java
 */
public class Damperstatus  implements java.io.Serializable {


     private Integer id;
     private String status;
     private String substatus;
     private boolean isenabled;
     private Set<Dampertest> dampertests = new HashSet<Dampertest>(0);

    public Damperstatus() {
    }

	
    public Damperstatus(Integer id, boolean isenabled) {
        this.id = id;
        this.isenabled = isenabled;
    }
    public Damperstatus(Integer id, String status, String substatus, boolean isenabled, Set<Dampertest> dampertests) {
       this.id = id;
       this.status = status;
       this.substatus = substatus;
       this.isenabled = isenabled;
       this.dampertests = dampertests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getSubstatus() {
        return this.substatus;
    }
    
    public void setSubstatus(String substatus) {
        this.substatus = substatus;
    }
    public boolean isIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(boolean isenabled) {
        this.isenabled = isenabled;
    }
    public Set<Dampertest> getDampertests() {
        return this.dampertests;
    }
    
    public void setDampertests(Set<Dampertest> dampertests) {
        this.dampertests = dampertests;
    }




}


