package com.thermalstrategies.eportal.model;
// Generated Oct 7, 2009 7:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Dampertype generated by hbm2java
 */
public class Dampertype  implements java.io.Serializable {


     private Integer id;
     private String aliasId;
     private String typeName;
     private boolean isenabled;
     private Set<Dampertest> dampertests = new HashSet<Dampertest>(0);

    public Dampertype() {
    }

	
    public Dampertype(Integer id, String typeName, boolean isenabled) {
        this.id = id;
        this.typeName = typeName;
        this.isenabled = isenabled;
    }
    public Dampertype(Integer id, String aliasId, String typeName, boolean isenabled, Set<Dampertest> dampertests) {
       this.id = id;
       this.aliasId = aliasId;
       this.typeName = typeName;
       this.isenabled = isenabled;
       this.dampertests = dampertests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAliasId() {
        return this.aliasId;
    }
    
    public void setAliasId(String aliasId) {
        this.aliasId = aliasId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public boolean isIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(boolean isenabled) {
        this.isenabled = isenabled;
    }
    public Set<Dampertest> getDampertests() {
        return this.dampertests;
    }
    
    public void setDampertests(Set<Dampertest> dampertests) {
        this.dampertests = dampertests;
    }




}


