package com.thermalstrategies.eportal.model;
// Generated Jan 5, 2011 12:40:35 PM by Hibernate Tools 3.2.1.GA



/**
 * Drawing generated by hbm2java
 */
public class Drawing  implements java.io.Serializable {


     private int id;
     private String drawingName;
     private Integer customerId;
     private String customerName;
     private Integer buildingId;
     private String buildingName;
     private Integer floorId;
     private String floorName;
     private byte[] drawingOriginal;
     private byte[] drawingThumb;
     private byte[] drawing;
     private Integer damperId;

    public Drawing() {
    }

	
    public Drawing(int id) {
        this.id = id;
    }
    public Drawing(int id, String drawingName, Integer customerId, String customerName, Integer buildingId, String buildingName, Integer floorId, String floorName, byte[] drawingOriginal, byte[] drawingThumb, byte[] drawing, Integer damperId) {
       this.id = id;
       this.drawingName = drawingName;
       this.customerId = customerId;
       this.customerName = customerName;
       this.buildingId = buildingId;
       this.buildingName = buildingName;
       this.floorId = floorId;
       this.floorName = floorName;
       this.drawingOriginal = drawingOriginal;
       this.drawingThumb = drawingThumb;
       this.drawing = drawing;
       this.damperId = damperId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDrawingName() {
        return this.drawingName;
    }
    
    public void setDrawingName(String drawingName) {
        this.drawingName = drawingName;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public Integer getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }
    public String getBuildingName() {
        return this.buildingName;
    }
    
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }
    public Integer getFloorId() {
        return this.floorId;
    }
    
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }
    public String getFloorName() {
        return this.floorName;
    }
    
    public void setFloorName(String floorName) {
        this.floorName = floorName;
    }
    public byte[] getDrawingOriginal() {
        return this.drawingOriginal;
    }
    
    public void setDrawingOriginal(byte[] drawingOriginal) {
        this.drawingOriginal = drawingOriginal;
    }
    public byte[] getDrawingThumb() {
        return this.drawingThumb;
    }
    
    public void setDrawingThumb(byte[] drawingThumb) {
        this.drawingThumb = drawingThumb;
    }
    public byte[] getDrawing() {
        return this.drawing;
    }
    
    public void setDrawing(byte[] drawing) {
        this.drawing = drawing;
    }
    public Integer getDamperId() {
        return this.damperId;
    }
    
    public void setDamperId(Integer damperId) {
        this.damperId = damperId;
    }




}


