package com.thermalstrategies.eportal.model;
// Generated Oct 7, 2009 7:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.sql.Blob;

/**
 * Building generated by hbm2java
 */
public class Pictures  implements java.io.Serializable {


     private Integer id;
     private Dampertest dampertest;
     private String name;
     private Blob image;

    public Pictures() {
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the dampertest
     */
    public Dampertest getDampertest() {
        return dampertest;
    }

    /**
     * @param dampertest the dampertest to set
     */
    public void setDampertest(Dampertest dampertest) {
        this.dampertest = dampertest;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the image
     */
    public Blob getImage() {
        return image;
    }

    /**
     * @param image the image to set
     */
    public void setImage(Blob image) {
        this.image = image;
    }
    




}


