package com.thermalstrategies.eportal.model;
// Generated Oct 7, 2009 7:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Integer aggregatedCount;
     private String projectNum;
     private String projectName;
     private Date dateReceived;
     private Date dateDue;
     private Integer totalEstimate;
     private Integer status;
     private String lastModifiedTs;
     private Date userLastModified;
     private String room;
     private String comments;
     private Boolean isEnabled;
     private String location;
     private String contact;
     private Set<Userlog> userlogs = new HashSet<Userlog>(0);
     private Set<Dampertest> dampertests = new HashSet<Dampertest>(0);

    public Project() {
    }

	
    public Project(Integer id, String projectNum, String projectName) {
        this.id = id;
        this.projectNum = projectNum;
        this.projectName = projectName;
    }
    public Project(Integer id, Customer customer, Integer aggregatedCount, String projectNum, String projectName, Date dateReceived, Date dateDue, Integer totalEstimate, Integer status, String lastModifiedTs, Date userLastModified, String room, String comments, Boolean isEnabled, String location, String contact, Set<Userlog> userlogs, Set<Dampertest> dampertests) {
       this.id = id;
       this.customer = customer;
       this.aggregatedCount = aggregatedCount;
       this.projectNum = projectNum;
       this.projectName = projectName;
       this.dateReceived = dateReceived;
       this.dateDue = dateDue;
       this.totalEstimate = totalEstimate;
       this.status = status;
       this.lastModifiedTs = lastModifiedTs;
       this.userLastModified = userLastModified;
       this.room = room;
       this.comments = comments;
       this.isEnabled = isEnabled;
       this.location = location;
       this.contact = contact;
       this.userlogs = userlogs;
       this.dampertests = dampertests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Integer getAggregatedCount() {
        return this.aggregatedCount;
    }
    
    public void setAggregatedCount(Integer aggregatedCount) {
        this.aggregatedCount = aggregatedCount;
    }
    public String getProjectNum() {
        return this.projectNum;
    }
    
    public void setProjectNum(String projectNum) {
        this.projectNum = projectNum;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public Date getDateReceived() {
        return this.dateReceived;
    }
    
    public void setDateReceived(Date dateReceived) {
        this.dateReceived = dateReceived;
    }
    public Date getDateDue() {
        return this.dateDue;
    }
    
    public void setDateDue(Date dateDue) {
        this.dateDue = dateDue;
    }
    public Integer getTotalEstimate() {
        return this.totalEstimate;
    }
    
    public void setTotalEstimate(Integer totalEstimate) {
        this.totalEstimate = totalEstimate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getLastModifiedTs() {
        return this.lastModifiedTs;
    }
    
    public void setLastModifiedTs(String lastModifiedTs) {
        this.lastModifiedTs = lastModifiedTs;
    }
    public Date getUserLastModified() {
        return this.userLastModified;
    }
    
    public void setUserLastModified(Date userLastModified) {
        this.userLastModified = userLastModified;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Boolean getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public Set<Userlog> getUserlogs() {
        return this.userlogs;
    }
    
    public void setUserlogs(Set<Userlog> userlogs) {
        this.userlogs = userlogs;
    }
    public Set<Dampertest> getDampertests() {
        return this.dampertests;
    }
    
    public void setDampertests(Set<Dampertest> dampertests) {
        this.dampertests = dampertests;
    }




}


