package com.thermalstrategies.eportal.model;
// Generated Oct 7, 2009 7:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer id;
     private String role;
     private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

	
    public Role(Integer id) {
        this.id = id;
    }
    public Role(Integer id, String role, Set<User> users) {
       this.id = id;
       this.role = role;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


