package com.thermalstrategies.eportal.model;
// Generated Feb 1, 2010 7:31:51 PM by Hibernate Tools 3.2.1.GA



/**
 * Site generated by hbm2java
 */
public class Site  implements java.io.Serializable {


    private Integer id;
    private String alias;
    private String description;
    private String name;
    private Customer customer;

    public Site() {
    }

    public Site(String alias, String description, String name, Customer customer) {
       this.alias = alias;
       this.description = description;
       this.name = name;
       this.customer = customer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the customer
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * @param customer the customer to set
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

}


