package com.thermalstrategies.eportal.model;
// Generated Feb 20, 2010 10:40:59 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Testcycle generated by hbm2java
 */
public class Testcycle  implements java.io.Serializable {


     private Integer id;
     private Building building;
     private String description;
     private Customer customer;
     private Date startdate;
     private Boolean complete;
     private Date finishdate;

    public Testcycle() {
    }

    public Testcycle(Building building, String description, Customer customer, Date startdate, Boolean complete, Date finishdate) {
       this.building = building;
       this.description = description;
       this.customer = customer;
       this.startdate = startdate;
       this.complete = complete;
       this.finishdate = finishdate;
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the building
     */
    public Building getBuilding() {
        return building;
    }

    /**
     * @param building the building to set
     */
    public void setBuilding(Building building) {
        this.building = building;
    }

    /**
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the customer
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * @param customer the customer to set
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * @return the startdate
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * @param startdate the startdate to set
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * @return the complete
     */
    public Boolean getComplete() {
        return complete;
    }

    /**
     * @param complete the complete to set
     */
    public void setComplete(Boolean complete) {
        this.complete = complete;
    }

    /**
     * @return the finishdate
     */
    public Date getFinishdate() {
        return finishdate;
    }

    /**
     * @param finishdate the finishdate to set
     */
    public void setFinishdate(Date finishdate) {
        this.finishdate = finishdate;
    }
   
    




}


