package com.thermalstrategies.eportal.model;
// Generated Oct 7, 2009 7:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Userlog generated by hbm2java
 */
public class Userlog  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Customer customer;
     private Building building;
     private Buildingfloor buildingfloor;
     private String sessionId;
     private Date loginTs;
     private Date logoutTs;

    public Userlog() {
    }

	
    public Userlog(Integer id) {
        this.id = id;
    }
    public Userlog(int id, User user, Customer customer, Building building, Buildingfloor buildingfloor, String sessionId, Date loginTs, Date logoutTs) {
       this.id = id;
       this.user = user;
       this.customer = customer;
       this.building = building;
       this.buildingfloor = buildingfloor;
       this.sessionId = sessionId;
       this.loginTs = loginTs;
       this.logoutTs = logoutTs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    public Building getBuilding() {
        return this.building;
    }
    
    public void setBuilding(Building building) {
        this.building = building;
    }
    public Buildingfloor getBuildingfloor() {
        return this.buildingfloor;
    }
    
    public void setBuildingfloor(Buildingfloor buildingfloor) {
        this.buildingfloor = buildingfloor;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public Date getLoginTs() {
        return this.loginTs;
    }
    
    public void setLoginTs(Date loginTs) {
        this.loginTs = loginTs;
    }
    public Date getLogoutTs() {
        return this.logoutTs;
    }
    
    public void setLogoutTs(Date logoutTs) {
        this.logoutTs = logoutTs;
    }

    /**
     * @return the customer
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * @param customer the customer to set
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }




}


