package com.thermalstrategies.eportal.model;
// Generated Oct 7, 2009 7:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Role role;
     private String userName;
     private String password;
     private String email;
     private String firstName;
     private String lastName;
     private String address1;
     private String address2;
     private String city;
     private String state;
     private String zip;
     private String phone;
     private Date dateCreatedTs;
     private Date lastModifiedTs;
     private boolean isenabled;
     private String sessionId;
     private Set<Userlog> userlogs = new HashSet<Userlog>(0);
     private Set<Dampertest> dampertests = new HashSet<Dampertest>(0);
     private Set<Buildingfloor> buildingfloors = new HashSet<Buildingfloor>(0);
     private String customers;
     private String includebuildingids;

    public User() {
    }

	
    public User(Integer id, Role role, boolean isenabled) {
        this.id = id;
        this.role = role;
        this.isenabled = isenabled;
    }
    
    public User(Integer id, Customer customer, Role role, String userName, String password, String email, String firstName, String lastName, String address1, String address2, String city, String state, String zip, String phone, Date dateCreatedTs, Date lastModifiedTs, boolean isenabled, String sessionId, Set<Userlog> userlogs, Set<Dampertest> dampertests, Set<Buildingfloor> buildingfloors, String includebuildingids) {
       this.id = id;
       this.customer = customer;
       this.role = role;
       this.userName = userName;
       this.password = password;
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.state = state;
       this.zip = zip;
       this.phone = phone;
       this.dateCreatedTs = dateCreatedTs;
       this.lastModifiedTs = lastModifiedTs;
       this.isenabled = isenabled;
       this.sessionId = sessionId;
       this.userlogs = userlogs;
       this.dampertests = dampertests;
       this.buildingfloors = buildingfloors;
       this.includebuildingids = includebuildingids;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getDateCreatedTs() {
        return this.dateCreatedTs;
    }
    
    public void setDateCreatedTs(Date dateCreatedTs) {
        this.dateCreatedTs = dateCreatedTs;
    }
    public Date getLastModifiedTs() {
        return this.lastModifiedTs;
    }
    
    public void setLastModifiedTs(Date lastModifiedTs) {
        this.lastModifiedTs = lastModifiedTs;
    }
    public boolean isIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(boolean isenabled) {
        this.isenabled = isenabled;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public Set<Userlog> getUserlogs() {
        return this.userlogs;
    }
    
    public void setUserlogs(Set<Userlog> userlogs) {
        this.userlogs = userlogs;
    }
    public Set<Dampertest> getDampertests() {
        return this.dampertests;
    }
    
    public void setDampertests(Set<Dampertest> dampertests) {
        this.dampertests = dampertests;
    }
    public Set<Buildingfloor> getBuildingfloors() {
        return this.buildingfloors;
    }
    
    public void setBuildingfloors(Set<Buildingfloor> buildingfloors) {
        this.buildingfloors = buildingfloors;
    }

    /**
     * @return the customers
     */
    public String getCustomers() {
        return customers;
    }

    /**
     * @param customers the customers to set
     */
    public void setCustomers(String customers) {
        this.customers = customers;
    }

    /**
     * @return the includebuildingids
     */
    public String getIncludebuildingids() {
        return includebuildingids;
    }

    /**
     * @param includebuildingids the includebuildingids to set
     */
    public void setIncludebuildingids(String includebuildingids) {
        this.includebuildingids = includebuildingids;
    }




}


